config/routes.rb
Bandwagon::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  devise_for :users
  resources :users
  resources :tshirts do
    get :preview
  end
  namespace :admin do
    resources :tshirts
  end
  root :to => "home#index"
end

app/models/ability.rb
class Ability

  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can [:new, :create], Tshirt
    if user.has_role? :admin
      can :manage, :all
    end
    can :manage, Tshirt do |tshirt|
      tshirt.user == user
    end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/tshirt.rb
class Tshirt < ActiveRecord::Base
  attr_accessible :description, :state, :title, :user_id, :artwork, :artwork_cache, :state_requested
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates_presence_of :title
  mount_uploader :artwork, ArtworkUploader
  belongs_to :user
  attr_accessor :state_requested

  state_machine :state, :initial => :unpublished do

    event :submit do
      transition [:unpublished, :rejected] => :submitted
    end

    event :reject do
      transition [:submitted] => :rejected
    end

    event :approve do
      transition [:submitted] => :published
    end

    event :unpublish do
      transition [:published] => :unpublished
    end

    before_transition :submitted => :rejected do |tshirt, transition|
      raise ArgumentError unless transition.args.first.is_a?(User)
      tshirt.can_change_state? transition.args.first, transition.from, transition.to
    end
  end

  def can_change_state?(user, from, to)
    valid_transitions = []
    if user.has_role? :admin
      valid_transitions = [
        ['submitted', 'rejected'],
        ['submitted', 'published'],
        ['rejected', 'submitted'],
        ['published', 'unpublished'],
        ['unpublished', 'submitted']
      ]
    else
      valid_transitions = [
        ['unpublished', 'submitted'],
        ['rejected', 'submitted']
      ]
    end
    valid_transitions.include? [from, to]
  end

  def available?
    state == 'published'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :confirmed_at

  before_create lambda { send(:skip_confirmation!) if Rails.env == 'test' }

  has_many :tshirts

  def can_change_state_for(object)
  end

end

app/controllers/admin/tshirts_controller.rb
module Admin

  class TshirtsController < ApplicationController

    load_and_authorize_resource

    def index
      @tshirts = Tshirt.all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/tshirts_controller.rb
class TshirtsController < ApplicationController

  respond_to :html, :json
  
  before_filter :authenticate_user!, :except => [:show]

  load_and_authorize_resource except: :show

  def new
    respond_with @tshirt
  end

  def create
    update_art_file_properties
    @tshirt.user_id = current_user.id
    if @tshirt.save
      flash[:notice] = "Tee created successfully"
      respond_with @tshirt, location: tshirt_preview_path(@tshirt)
    else
      respond_with @tshirt
    end
  end

  def preview
    @tshirt = Tshirt.find params[:tshirt_id]
  end

  def show
    @tshirt = Tshirt.find params[:id]
  end

  def edit
  end

  def update
    update_art_file_properties
    if @tshirt.update_attributes params[:tshirt]
      if params[:tshirt][:state_requested]
        transition = @tshirt.state_transitions.
          detect{|s|s.to == params[:tshirt][:state_requested].downcase}
        transition.perform(current_user) if transition.present?
      end
      flash[:notice] = "Tee updated successfully" 
      respond_with @tshirt, location: edit_tshirt_path(@tshirt)
    else
      respond_with @tshirt, location: edit_tshirt_path(@tshirt)
    end
  end

  def destroy
    @tshirt.destroy
    if @tshirt.destroyed?
      flash[:notice] = "Tee deleted successfully"
      respond_with @tshirt, location: root_path 
    else
      respond_with @tshirt
    end
  end

  private

  def update_art_file_properties
    artwork_params = params[:tshirt][:artwork]
    if artwork_params.present?
      @tshirt.art_file_name = artwork_params.original_filename 
      @tshirt.art_content_type = artwork_params.content_type
      @tshirt.art_file_size = artwork_params.size
      @tshirt.art_updated_at = Time.now
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tshirts_helper.rb
module TshirtsHelper

  def state_button_label event
    case event
    when :submit
      "Submit for Approval"
    when :reject
      "Reject Tee"
    when :approve
      "Approve Tee"
    when :unpublish
      "Unpublish Tee"
    end
  end
end

app/views/admin/tshirts/index.html.haml
%h2
  Tshirts
- if @tshirts.empty?
  No tshirts yet
- else
  %table.table
    %tr
      %th
        Created
      %th
        State
      %th
        User
      %th
        Title
      %th{style: "width: 100%"}
        Transfer (PDF)
    - @tshirts.each do |tshirt|
      %tr{:"data-tshirt-id" => tshirt.id}
        %td{style: "white-space: nowrap"}
          = "#{tshirt.created_at.to_s(:long)} (#{time_ago_in_words tshirt.created_at} ago)"
        %td
          = tshirt.state.upcase
        %td
          = tshirt.user.email
        %td
          - if tshirt.state != "published"
            = link_to tshirt.title, tshirt_preview_path(tshirt)
          - else
            = link_to tshirt.title, tshirt
        %td
          = link_to raw("11&times;17"), tshirt.artwork.transfer_11x17.url, class: "transfer-link"

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Bandwagon", root_path, :class => 'brand'
%ul.nav.pull-right
  - if user_signed_in?
    %li
      = link_to "Create a Tee", new_tshirt_path
    %li
      = link_to "My Tees", tshirts_path
    - if current_user.has_role? :admin
      %li.dropdown
        = link_to "#", class: "dropdown-toggle", :"data-toggle"=> "dropdown" do
          Admin
          %b.caret
        %ul.dropdown-menu
          %li
            = link_to "Tshirts", admin_tshirts_path
          %li
            = link_to "Users", users_path
    %li.dropdown
      = link_to "#", class: "dropdown-toggle", :"data-toggle" => "dropdown" do
        = current_user.email
        %b.caret
      %ul.dropdown-menu
        %li
          = link_to 'Edit Account', edit_user_registration_path
    %li
      = link_to destroy_user_session_path, :method=> 'delete' do
        Sign Out
        %i.icon-signout
  - else
    %li
      = link_to 'Sign Up', new_user_registration_path
    %li
      = link_to new_user_session_path do
        Sign In
        %i.icon-signin

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Bandwagon"
      %meta{:content => content_for?(:description) ? yield(:description) : "Bandwagon", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .row
          .span12
            = render 'layouts/messages'
            = yield
        %footer

app/views/tshirts/_show.html.haml
.row
  .span9
    %h2
      = @tshirt.title
    .row
      .span4
        %p
          - if @tshirt.description.present?
            = @tshirt.description
      .span5
        - if @tshirt.artwork.present?
          = image_tag @tshirt.artwork.preview
  .span3
    %h3
      Pre-Order This Tee!
    = simple_form_for :order do |f|
      = f.input :quantity, collection: 1..100, as: :select
      = f.input :shirt, collection: ["Hanes Tagless", "Fruit of the Loom", "American Apparel"], as: :select
      = f.input :size, collection: ["S", "M", "L", "XL", "XXL"], as: :select
      = f.submit "Place My Pre-Order", class: "btn btn-primary btn-large"

app/views/tshirts/_state_buttons.html.haml
- @tshirt.state_transitions.each do |transition|
  = simple_form_for @tshirt, html: { style: "display: inline" } do |f|
    - if @tshirt.can_change_state?(current_user, transition.from, transition.to)
      = f.input :state_requested, as: :hidden, input_html: { value: transition.to }
      = f.submit state_button_label(transition.event), class: "btn state-button"

app/views/tshirts/edit.html.haml
.row
  .span6
    = simple_form_for @tshirt do |f|
      %fieldset
        %legend Update Your Tee
        .alert
          After you've made your changes click <strong>&ldquo;Preview Pre-Order&rdquo;</strong>
        = f.input :title, label: "Tee Title", input_html: { class: "span6" }
        = f.input :description, label: "Tee Description", input_html: { rows: 4, class: "span6" }
        .control-group
          = f.label :artwork, "Artwork File"
          .controls
            = f.file_field :artwork, style: 'display: none'
            .input-append
              %input#artwork-file.input-large{type: "text", value: "#{@tshirt.art_file_name}"}
              %a.btn{onclick: "$('#tshirt_artwork').click();"} Browse
            .help-block
              Updating this source artwork file will also update the original
              image and preview images.
            = f.hidden_field :artwork_cache
            :javascript
              $('#tshirt_artwork').change(function() {
                $('#artwork-file').val($(this).val().replace(/C:\\fakepath\\/,''));
              });
        .form-actions
          = link_to "Preview Pre-Order", tshirt_preview_path(@tshirt), class: "btn btn-success btn-large", style: "margin-right: 1em"
          = f.submit "Update My Tee", class: "btn btn-primary"
          or
          = link_to "Delete Tee", @tshirt, method: :delete, class: "btn btn-danger", confirm: "Are you sure?"
  .span6
    %ul.nav.nav-tabs
      %li.active
        = link_to "Preview Image", "#preview-image", :"data-toggle" => "tab"
      %li
        = link_to "Original Image", "#original-image", :"data-toggle" => "tab"

    - if @tshirt.artwork.present?
      .tab-content
        .tab-pane.active#preview-image
          - if @tshirt.artwork.preview.present?
            .row
              .offset1.span5
                = image_tag @tshirt.artwork.preview, class: "span4"
        .tab-pane#original-image
          - if @tshirt.artwork.present?
            .row
              .offset1.span5
                = image_tag @tshirt.artwork, class: "span4"

app/views/tshirts/index.html.haml
%h2
  My Tees
%hr/
- current_user.tshirts.each do |tshirt|
  .row
    .offset1.span5
      = link_to(image_tag(tshirt.artwork.preview), edit_tshirt_path(tshirt))
    .offset1.span5
      %h3
        = tshirt.title
      %h4
        0 Pre-Orders

app/views/tshirts/new.html.haml
= simple_form_for @tshirt do |f|
  %fieldset
    %legend Create a Tee
    = f.input :title, label: "Tee Title"
    = f.input :description, label: "Tee Description", input_html: { rows: 4 }
    .control-group
      = f.label :artwork, "Artwork File"
      .controls
        = f.file_field :artwork, style: 'display: none'
        .input-append
          %input#artwork-file.input-large{type: "text", value: "#{@tshirt.art_file_name}"}
          %a.btn{onclick: "$('#tshirt_artwork').click();"} Browse
        = f.hidden_field :artwork_cache
        :javascript
          $('#tshirt_artwork').change(function() {
            $('#artwork-file').val($(this).val().replace(/C:\\fakepath\\/,''));
          });
    .form-actions
      = f.submit "Create My Tee", class: "btn btn-primary"

app/views/tshirts/preview.html.haml
.row
  .span12
    .alert
      This a a preview of <strong>&ldquo;#{@tshirt.title}&rdquo;</strong>. 
      To make changes click the &ldquo;Change My Tee&rdquo; button. When 
      you're changes are complete click &ldquo;Submit for Approval.&rdquo;
    - if !@tshirt.description.present?
      .alert.alert-info
        This tee is missing a description. 
        <strong>#{link_to "Click here", edit_tshirt_path(@tshirt)}</strong>
        to add one.
.row
  .span12
    = link_to "Change My Tee", edit_tshirt_path(@tshirt), class: "btn btn-primary"
    = render partial: "state_buttons", locals: { tshirt: @tshirt }
%hr/
= render partial: "show"

app/views/tshirts/show.html.haml
- if @tshirt.available?
  = render partial: "show"
- else
  .alert
    =t :tee_unavailable

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/index.html.haml
%h2 Users
.row
  .span12
    %table.table
      %thead
        %tr
          %th Name 
          %th Email
          %th Registered
          %th Role
          %th{style: "width: 100%"}
      %tbody
        - @users.each do |user|
          %tr
            %td{style: "white-space: nowrap; min-width: 180px"}
              = link_to user.name, user
            %td{style: "white-space: nowrap; min-width: 180px"}
              = user.email
            %td{style: "white-space: nowrap; min-width: 90px"}
              = user.created_at.to_date
            %td{style: "white-space: nowrap; min-width: 90px"}
              = user.roles.first.name.titleize unless user.roles.first.nil?
            %td
              %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change Role
              = render user
              = link_to("Delete User", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini btn-danger') unless user == current_user

app/views/users/show.html.haml
%h2 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}